#!/usr/bin/env python3

import argparse, socket, time, json, select, struct, sys, math, os

BROADCAST = "FFFF"

class Replica:
    def __init__(self, port, id, others):
        self.port = port
        self.id = id
        self.others = others

        self.leader = '0000'
        self.store = {}

        self.socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        self.socket.bind(('localhost', 0))

        print("Replica %s starting up" % self.id, flush=True)
        hello = { "src": self.id, "dst": BROADCAST, "leader": BROADCAST, "type": "hello" }
        self.send(hello)
        print("Sent hello message: %s" % hello, flush=True)

    def send(self, message):
        self.socket.sendto(json.dumps(message).encode('utf-8'), ('localhost', self.port))

    def run(self):
        while True:
            data, addr = self.socket.recvfrom(65535)
            msg = data.decode('utf-8')

            #print("Received message '%s'" % (msg,), flush=True)
            
            data_msg = json.loads(msg)

            if self.id != self.leader and (data_msg['type'] == 'get' or 'put'):
                message = {}
                message['src'] = data_msg['dst']
                message['dst'] = data_msg['src']
                message['leader'] = self.leader
                message['type'] = 'redirect'
                message['MID'] = data_msg['MID']
                self.send(message)

            elif data_msg['type'] == 'put':
                self.put_message(data_msg)
            if data_msg['type'] == 'get':
                self.get_message(data_msg)     

    def put_message(self, msg) :
        self.store[msg['key']] = msg['value']
        message = {}
        message['src'] = msg['dst']
        message['dst'] = msg['src']
        message['leader'] = self.leader
        message['type'] = 'ok'
        message['MID'] = msg['MID']
        message['key'] = msg['key']
        message['value'] = msg['value']
        
        self.send(message)
        if msg['key'] not in self.store:
            self.append_entries_message(msg)
        self.fail_message(msg)
            
        
        # message2 = {}
        # message2['src'] = msg['dst']
        # message2['dst'] = 'FFFF'
        # message2['leader'] = self.leader
        # message2['type'] = 'fail'
        # message2['MID'] = msg['MID']
        # self.send(message2)
    
    def get_message(self, msg) :
        message = {}
        message['src'] = msg['dst']
        message['dst'] = msg['src']
        message['leader'] = self.leader
        message['type'] = 'ok'
        message['MID'] = msg['MID']
        
        if msg['key'] in self.store:
            message['value'] = self.store.get(msg['key'])
            self.send(message)
        else:
            self.fail_message(msg)
    
    def fail_message(self, msg):
        message = dict()
        message['src'] = msg['dst']
        message['dst'] = 'FFFF'
        message['leader'] = self.leader
        message['type'] = 'fail'
        message['MID'] = msg['MID']
        self.send(message)
        
    def append_entries_message(self, msg):
        message = {}
        message['src'] = self.id
        message['dst'] = msg['src']
        message['type'] = 'AppendEntries'
        message['leader'] = self.leader
        message['MID'] = msg['MID']
        self.send(message)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='run a key-value store')
    parser.add_argument('port', type=int, help="Port number to communicate")
    parser.add_argument('id', type=str, help="ID of this replica")
    parser.add_argument('others', metavar='others', type=str, nargs='+', help="IDs of other replicas")
    args = parser.parse_args()
    replica = Replica(args.port, args.id, args.others)
    replica.run()
